name: justfile

on: push

# ensure multiple CI processes are not running analysis on contracts
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true
  
env:
  CI: true
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  PULL_NUMBER: ${{ github.event.pull_request.number }}
  RUN_ID: ${{ github.run_id }}

jobs:
  pipeline:
    name: Justfile ${{ matrix.just-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        just-version: [0.5.11, 0.6.1, 0.7.3, 0.8.7, 0.9.9, 0.10.0]



    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test
      run: |
        [ "$(just --justfile __tests__/justfile)" = "Test..." ]
      shell: bash

  test-version:
    needs: pipeline
    strategy:
      matrix:
        just-version: [0.5.11, 0.6.1, 0.7.3, 0.8.7, 0.9.9, 0.10.0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
      with:
        just-version: ${{ matrix.just-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check version
      run: just --version | grep -E "^just v?${{ matrix.just-version }}$"
    - name: Test
      run: |
        [ "$(just --justfile __tests__/justfile)" = "Test..." ]
        [ "$(just --justfile justfile)" = "Test..." ]
