name: justfile

on: push

jobs:
  pipeline:
    name: Justfile ${{ matrix.just-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup just
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test
      run: |
        [ "$(just --justfile tests/Justfile)" = "Test..." ]
      shell: bash

  test-version:
    needs: test-latest
    strategy:
      matrix:
        just-version: [0.5.11, 0.6.1, 0.7.3, 0.8.7, 0.9.9, 0.10.0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run self
      uses: ./
      with:
        just-version: ${{ matrix.just-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check version
      run: just --version | grep -E "^just v?${{ matrix.just-version }}$"
    - name: Test
      run: |
        [ "$(just --justfile __tests__/justfile)" = "Test..." ]
        [ "$(just --justfile justfile)" = "Test..." ]